name: Create automatic PR

on:
  push:
    branches:
      - main

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update Author Information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git add AUTHOR
          git commit -m "Update author information"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.ref_name }}
          base: main
          title: "Update author information"
          body: "This is an automatic PR"
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
