name: Create automatic PR

on:
  push:
    branches:
      - main

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Extract Git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name:  Update Author Information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise a PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "auto-pr-branch"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body:
            This is a automatic PR
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true